# Auto generated by ascan, alpha version.
# - ver: 0.0.1
# - date: 2019/11/6
# - url: git@github.com:ABackerNINI/ascan.git

# Build details

_CXX                    = g++
_CXXFLAGS               = -W -Wall -g
_BD						= ./build

# Compile to objects

$(_BD)/%.o: %.cpp
	$(_CXX) $(_CXXFLAGS) -c -o $@ $<

# Build Executable

.PHONY: all
all: ascan

.PHONY: BD
BD:
	mkdir $(_BD)

.PHONY: rebuild
rebuild: clean all

# Executable 1

_exe1 = ascan
_objs1 = ascan.o mfile.o common.o parser.o cfile.o config.o
_objs1_bd = $(_objs1:%=$(_BD)/%)

ascan: BD $(_objs1_bd)
	$(_CXX) $(_CXXFLAGS) -o $(_exe1) $(_objs1_bd)

# Dependencies

$(_BD)/mfile.o: mfile.h cfile.h config.h flags.h
$(_BD)/common.o: common.h
$(_BD)/parser.o: parser.h
$(_BD)/cfile.o: common.h cfile.h parser.h
$(_BD)/config.o: config.h parser.h
$(_BD)/ascan.o: ascan.h cfile.h config.h mfile.h common.h flags.h

# Clean up

.PHONY: clean
clean:
	rm -f "$(_exe1)" $(_objs1_bd)
