# Auto generated by ascan, alpha version.

# Build details

_CXX                    = g++
_CXXFLAGS               = -W -Wall

# Compile to objects

%.o: %.cpp
	$(_CXX) $(_CXXFLAGS) -c -o $@ $<

# Build Executable

# executable 1
_exe1 = ascan
_objects1 = main.o cfiles.o parser.o config.o ascan.o

.PHONY: ascan
ascan: $(_objects1)
	$(_CXX) $(_CXXFLAGS) -o $(_exe1) $(_objects1)

# Dependencies

cfiles.o: cfiles.h parser.h
commom.o: common.h
parser.o: parser.h
config.o: config.h parser.h
ascan.o: ascan.h cfiles.h config.h
main.o: cfiles.h ascan.h config.h parser.h

# Clean up

.PHONY: clean
clean:
	rm -f "$(_exe1)" $(_objects1)
